apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet:
        tlas:
        - name: target_registry
          value: docker.io
    path: manifest/service-mesh/istio
    repoURL: https://github.com/tmax-cloud/argocd-installer
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
