apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-kafka-cluster-oprerator
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: kafka
    server: 'https://kubernetes.default.svc'
  source:
    path: manifest/strimzi-kafka-cluster-oprerator
    repoURL: 'https://github.com/tmax-cloud/argocd-installer'
    targetRevision: main
  project: default
