apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ cluster name }}-applications
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - shared-values.yaml
        - single-values.yaml
      parameters:
        - name: spec.destination.name
          value: cluster_name
        - name: global.privateRegistry
          value: testregistry.com
    path: application/helm
    repoURL: https://github.com/tmax-cloud/argocd-installer
    targetRevision: HEAD