apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
spec:
  destination:
    namespace: argocd
  project: default
  source:
    helm:
      valueFiles:
        - single-values.yaml
    path: application/helm
    repoURL: https://gitlab.ckcloud.org/root/argocd-installer.git
    targetRevision: shkim/appofapp