apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    # {{ cluster namespace }}-{{ cluster name }}로 변경
    cluster: single
    appType: app-of-apps
  # {{ cluster namespace }}-{{ cluster name }}-applications로 변경
  name: single-applications
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - shared-values.yaml
        - single-values.yaml
      parameters:
        - name: global.clusterName
          # target cluster 이름으로 변경
          value: cluster-name
        - name: global.clusterNamespace
          # target cluster의 네임스페이스로 변경
          value: cluster-namespace
        - name: global.privateRegistry
          # target registry 주소로 변경
          value: test-registry.com
        - name: global.adminUser
          # 해당 클러스터의 admin 계정으로 변경
          value: test@test.co.kr
        - name: modules.gatewayBootstrap.console.subdomain
          # 콘솔이 사용할 subdomain으로 변경
          value: console
        - name: modules.hyperAuth.subdomain
          # HyperAuth가 사용할 subdomain으로 변경
          value: hyperauth
        - name: modules.efk.kibana.subdomain
          # Kibana가 사용할 subdomain으로 변경
          value: kibana
        - name: modules.grafana.subdomain
          # Grafana가 사용할 subdomain으로 변경
          value: grafana
        - name: modules.serviceMesh.jaeger.subdomain
          # Jaeger가 사용할 subdomain으로 변경
          value: jaeger
        - name: modules.serviceMesh.kiali.subdomain
          # Kiali가 사용할 subdomain으로 변경
          value: kiali
        - name: modules.cicd.subdomain
          # Cicd-operator webhook이 사용할 subdomain으로 변경
          value: cicd-webhook
        - name: modules.opensearch.dashboard.subdomain
          # OpenSearch가 사용할 subdomain으로 변경
          value: opensearch-dashboard
        - name: modules.hyperregistry.core.subdomain
          # Hyperregistry core가 사용할 subdomain으로 변경
          value: hyperregistry
        - name: modules.hyperregistry.notary.subdomain
          # Hyperregistry notary가 사용할 subdomain으로 변경
          value: hyperregistry-notary
        - name: modules.hyperregistry.storageClass
          # Hyperregistry에서 postgres외의 pvc의 storage class로 변경
          # aws의 경우 efs-sc-0, 그외에는 nfs
          value: nfs
        - name: modules.hyperregistry.storageClassDatabase
          # Hyperregistry에서 postgres의 pvc의 storage class로 변경
          # aws의 경우 efs-sc-999, 그외에는 nfs
          value: nfs
        - name: modules.gitlab.subdomain
          # gitlab이 사용할 subdomain으로 변경
          value: gitlab
        - name: modules.nfs.server
          # nfs provisioner가 사용할 nfs server, ex: 192.168.7.16
          value: 192.168.7.16
        - name: modules.nfs.path
          # nfs provisioner가 사용할 nfs server의 path, ex: /mnt/nfs-shared-dir
          value: /nfs-storage
        - name: modules.cephfs.clusterId
          # csi-config-map 에서 명시한 clusterID(fsid)
          value: 50611be6-33b3-11eb-a5cb-0894ef32cba4
        - name: modules.rbd.clusterId
          # csi-config-map 에서 명시한 clusterID(fsid)
          value: 50611be6-33b3-11eb-a5cb-0894ef32cba4
    path: application/helm
    # 환경에 맞게 url 주소 변경 필요
    repoURL: https://github.com/tmax-cloud/argocd-installer
    # 환경에 맞게 target branch/release 변경 필요
    targetRevision: HEAD
