apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    cluster: single
    appType: app-of-apps
  name: single-applications
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - shared-values.yaml
        - single-values.yaml
      parameters:
        - name: global.clusterName
          # target cluster 이름으로 변경
          value: cluster-name
        - name: global.clusterNamespace
          # target cluster의 네임스페이스로 변경
          value: cluster-namespace
        - name: global.privateRegistry
          # target registry 주소로 변경
          value: test-registry.com
        - name: global.adminUser
          # 해당 클러스터의 admin 계정으로 변경
          value: test@test.co.kr
    path: application/helm
    # 환경에 맞게 url 주소 변경 필요
    repoURL: https://github.com/tmax-cloud/argocd-installer
    # 환경에 맞게 target branch/release 변경 필요
    targetRevision: HEAD