apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager-main
  namespace: monitoring
---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
  annotations:
    kubernetes.io/service-account.name: alertmanager-main
type: kubernetes.io/service-account-token
