apiVersion: v1
kind: Service
metadata:
  labels:
    component: kube-scheduler
  name: kube-scheduler-prometheus-discovery
  namespace: kube-system
spec:
  ports:
  - name: http-metrics
    port: 10251
    protocol: TCP
    targetPort: 10251
  selector:
    component: kube-scheduler
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
