apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: v0.51.2
  name: prometheus-operator
  namespace: monitoring
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-operator
  namespace: monitoring
  annotations:
    kubernetes.io/service-account.name: prometheus-operator
type: kubernetes.io/service-account-token
