{{- if .Values.modules.imageValidatingWebhook.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-validating-webhook
  namespace: argocd
spec:
  destination:
    namespace: registry-system
    {{- if eq .Values.spec.destination.type "name" }}
    name: {{ .Values.spec.destination.clusterInfo }}
    {{- else if eq .Values.spec.destination.type "server" }}
    server: {{ .Values.spec.destination.clusterInfo }}
    {{- end }}
  project: {{ .Values.spec.project }}
  source:
    path: manifest/image-validating-webhook
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
{{- end }}