{{- if .Values.modules.strimziKafka.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-kafka-cluster-oprerator
  namespace: argocd
spec:
  destination:
    namespace: kafka
    {{- if eq .Values.spec.destination.type "name" }}
    name: {{ .Values.spec.destination.clusterInfo }}
    {{- else if eq .Values.spec.destination.type "server" }}
    server: {{ .Values.spec.destination.clusterInfo }}
    {{- end }}
  project: {{ .Values.spec.project }}
  source:
    directory:
      jsonnet:
        tlas:
          - name: is_offline
            value: {{ .Values.global.network.disabled }}
          - name: private_registry
            value: {{ .Values.global.privateRegistry }}
    path: manifest/strimzi-kafka-cluster-oprerator
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
{{- end }}