apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: monitoring
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    kubernetes.io/service-account.name: grafana
type: kubernetes.io/service-account-token
