apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet:
        tlas:
        - name: is_offline
          value: "false"
        - name: private_registry
          value: 172.22.6.22:5000
    path: application/jsonnet
    repoURL: https://github.com/tmax-cloud/argocd-installer
    targetRevision: main