apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonar-ingress
  namespace: sonarqube
  labels:
    ingress.tmaxcloud.org/name: sonarqube
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: tmax-cloud
  {{- if .Values.tls.enabled }}
  tls:
  - hosts:
    - sonarqube.{{ .Values.ingress.hosts.domain }}
  {{- end }}
  rules:
    - host: sonarqube.{{ .Values.ingress.hosts.domain }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: sonarqube-service
                port:
                  number: 9000