spec:
  source:
    # description
    # https연결만 사용 가능합니다.
    # gitlab의 경우, url 마지막에 '.git' suffix를 붙여주셔야 합니다
    repoURL: https://github.com/tmax-cloud/argocd-installer
    # description: target branch or release name
    targetRevision: HEAD
    
global:
  # 현재 지원하는 timeZone value
  # UTC (default)
  # Asia/Seoul
  timeZone: UTC
  network:
    # 폐쇄망일경우 true
    disabled: false
 